### ISSUE TITLE
Responsive view registration form

### ISSUE THREAD

**Issue by dickypuja** [laravolt/auth#16]

**Comment by uyab** [comment]
Hi @dickypuja , thank you for submitting issue. Could you provide a screenshot or two related to this issue?

**Comment by dickypuja** [comment]
![screenshot_1](https://user-images.githubusercontent.com/32038843/57126984-234ae900-6db9-11e9-8252-e42864669c2d.png)

**Comment by uyab** [comment]
Fixed in 4.6.12
